### ISSUE TITLE
addition of else

### ISSUE THREAD

**Issue by yogthos** [danlarkin/clabango#2]
Would it be possible to add else in addition to if as in Django?

```
{% if athlete_list %}
    Number of athletes: {{ athlete_list|length }}
{% else %}
    No athletes.
{% endif %}
```

**Comment by danlarkin** [comment]
Yes, this would be a welcome addition. Are you up for having a go at the implementation?

**Comment by yogthos** [comment]
I could definitely give it a shot :) where's a good place to start looking at adding it?

**Comment by danlarkin** [comment]
https://github.com/danlarkin/clabango/blob/master/src/clabango/tags.clj#L51 and L69

That's where the if/ifequal tags live. I think you'll have to add some extra parsing stage to catch that there's an "else" in between the if/endif, since the way the parser works is when it encounters an opening tag it scans forward for the appropriate closing tag and sends that whole block of text off to be handled.

**Comment by yogthos** [comment]
awesome, I'll take a look today :)

**Comment by danlarkin** [comment]
Thanks for your PR! I took the liberty to do some cleanup, but thanks a bunch for getting the ball rolling on this

**Comment by yogthos** [comment]
I really enjoying using Clabango, so thanks for making it and glad to be a bit of help. :)
